const verbComplementKinds = {
  buty: ["place_at", "adverb"],
  maty: ["object", "adverb"],
  khotity: ["object", "infinitive", "adverb"],
  mohty: ["infinitive", "adverb"],
  lyubyty: ["object", "infinitive", "adverb"],
  yisty: ["object", "place_at", "adverb"],
  pyty: ["object", "place_at", "adverb"],
  hotuvaty: ["object", "place_at", "adverb"],
  kupuvaty: ["object", "place_at", "adverb"],
  platyty: ["place_at", "adverb"],
  zamovljaty: ["object", "place_at", "adverb"],
  zhyty: ["place_at", "adverb"],
  meshkaty: ["place_at", "adverb"],
  spaty: ["place_at", "adverb"],
  yty: ["place_to", "adverb"],
  jikhaty: ["place_to", "adverb"],
  robyty: ["object", "place_at", "adverb"],
  hovoryty: ["adverb"],
  pysaty: ["object", "place_at", "adverb"],
  kazaty: ["adverb"],
  pytaty: ["adverb"],
  slukhaty: ["object", "place_at", "adverb"],
  rozumity: ["object", "adverb"],
  znaty: ["object", "adverb"],
  dumaty: ["adverb"],
  bachyty: ["object", "place_at", "adverb"],
  dopomahaty: ["adverb"],
  davaty: ["object", "adverb"],
  braty: ["object", "place_at", "adverb"],
  pratsyuvaty: ["place_at", "adverb"],
  chekaty: ["object", "place_at", "adverb"],
  vyvchaty: ["object", "place_at", "adverb"],
  chytaty: ["object", "place_at", "adverb"],
  vidpochyvaty: ["place_at", "adverb"],
  huljaty: ["place_at", "adverb"],
  prykhodyty: ["place_to", "adverb"],
  spivaty: ["object", "place_at", "adverb"],
};

export default verbComplementKinds;
